### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by fawind** [eguller/hntoplinks#31]
I am getting an Application Error when visiting [hntoplinks.com](http://www.hntoplinks.com) since yesterday.

It shows the default [Heroku error page](https://devcenter.heroku.com/articles/error-pages) saying:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by eguller** [comment]
hntoplinks is hosted on Heroku (Free plan), which gives 550 dyno hours per month. This was enough for hntoplinks till last year, but it became popular and started exceed free plan in last 5-7 days of the month. It will be available again at the beginning of next month. Meanwhile I will check whether I can find a better free hosting or not.

**Comment by ad-si** [comment]
Yes please! I'm really missing it 😭

**Comment by mandriv** [comment]
@eguller have you considered using DigitalOcean droplets? They are around ~5$ for the cheapest plan. You should also consider accepting donations, I use your app daily.

**Comment by ad-si** [comment]
Looks like https://hn.algolia.com/?sort=byPopularity&page=0&dateRange=last24h&type=all does the same thing btw.

**Comment by Mennaruuk** [comment]
@eguller The website is down again ;( Is there any hope of its coming back?

**Comment by eguller** [comment]
hello i moved it to a new stack on heroku. previous cedar stack has been retired by heroku. 
unfortunately, in november heroku will suspend free account.
i will migrate application to digital ocean probably before november. 
now just migrated to a new stack on heroku free plan.
