### ISSUE TITLE
hntoplinks.com down

### ISSUE THREAD

**Issue by zakiaziz** [eguller/hntoplinks#34]
Hi, just wanted to reach out because hntoplinks.com has been down for a couple of weeks. I'm wondering if there are plans to bring it back up

**Comment by EngineerReversed** [comment]
Yes, I am getting this error.

![image](https://user-images.githubusercontent.com/20800767/117608888-93e12900-b17c-11eb-904c-66d042a7dc01.png)

**Comment by eguller** [comment]
hello it is up again.

**Comment by eguller** [comment]
hello application is shutdown by heroku at the end of month (last 5 days). 
buy anyway heroku free plans will be decommissioned at the end of Novembe.
I moved application to Digital Ocean, there should not be any downtime from now on.
